### ISSUE TITLE
[CI] Speed up CI using GitHub build matrix

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#359]
Speed up CI using GitHub [build matrix](https://docs.github.com/en/actions/using-workflows/advanced-workflow-features#using-a-build-matrix)

**Comment by annieappflowy** [comment]
> I will give a try

Awesome. I have assigned it to you. If you need help, please reach out to @tsuiyuenhong on Discord.

**Comment by rubiagatra** [comment]
Could you give me some context @annieappflowy which GitHub actions do you need to use the GitHub matrix?
```
.github/workflows
├── ci.yaml
├── commit_lint.yml
├── dart_lint.yml
├── dart_test.yml
├── release.yml
├── release_docker.yml
├── rust_lint.yml
├── rust_test.yml
└── translation_notify.yml
```

And what kind of matrix? Rust version? flutter version? or CPU architecture matrix?

**Comment by tsuiyuenhong** [comment]
> Could you give me some context @annieappflowy which GitHub actions do you need to use the GitHub matrix?
> 
> ```
> .github/workflows
> ├── ci.yaml
> ├── commit_lint.yml
> ├── dart_lint.yml
> ├── dart_test.yml
> ├── release.yml
> ├── release_docker.yml
> ├── rust_lint.yml
> ├── rust_test.yml
> └── translation_notify.yml
> ```
> 
> And what kind of matrix? Rust version? flutter version? or CPU architecture matrix?

Hi, rubiagatra. I thought the title `[CI] Speed up CI using GitHub build matrix` is a little bit puzzling. In the first part, we want to manage the build scripts by matrix, like platforms. And as the second part, we want to reduce the cost time of some scripts, like `ci.yaml`, `dart_test.yaml`, and `rust_test.yaml`. But now I still have no idea how to optimize them. Would you mind doing some research and we keep discussing it after that?

**Comment by rubiagatra** [comment]
Ahh Thank you @tsuiyuenhong, I think its little bit more clear.
Sure I'll explore something this weekend, Maybe on Monday I'll let you know

**Comment by annieappflowy** [comment]
Hi @rubiagatra, any update on this?

**Comment by rubiagatra** [comment]
I have been a little bit busy in the past 3 months, I'll check this on Sunday. If anyone wants to take a stab at it, go ahead!

**Comment by rubiagatra** [comment]
I think for `build` matrix is already done yeah @annieappflowy @LucasXu0? or do you want windows support too?
```
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_profile: development-linux-x86_64
          - os: macos-latest
            flutter_profile: development-mac-x86_64
    runs-on: ${{ matrix.os }}
```
To make it a faster for cargo build, I think we need to disable incremental build.
