### ISSUE TITLE
[Bug] Failed to download the file

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#6019]
### Bug Description

I uploaded a file using /file, and then clicked the file to jump to the browser, but the browser returned the following content. I am using the self-hosted appflowy
![image](https://github.com/user-attachments/assets/3ed46b7f-4b9b-4c7f-ab4e-5023a1a5b515)

### How to Reproduce

Using the self-hosted appflowy, upload the file and click on the file

### Expected Behavior

Can download files normally

### Operating System

mac

### AppFlowy Version(s)

0.6.7

**Comment by khorshuheng** [comment]
Can you share your nginx and Appflowy configuration?

**Comment by smartyhero** [comment]
I did not use the official docker-compose, and I did not use Nginx. I used envoy. The following is my envoy configuration
```yml
admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901

static_resources:
  # https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#example-one-static-resource
  secrets:
    - name: smartyhero
      tls_certificate:
        certificate_chain:
          filename: "/usr/local/appflowy/ssl/smartyhero.pem"
        private_key:
          filename: "/usr/local/appflowy/ssl/smartyhero-key.pem"
        watched_directory:
          path: /usr/local/appflowy/ssl/
  listeners:
    - name: http
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                      - "*"
                      routes:
                        - match:
                            prefix: "/"
                          redirect:
                            https_redirect: true
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - name: https
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_ws_to_ws
                codec_type: AUTO
                use_remote_address: true # 开始x-forwarded-for header skip_xff_append必须为false
                upgrade_configs:
                  - upgrade_type: websocket
                skip_xff_append: false
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /usr/local/appflowy/logs/envoy/access.json # 修改日志文件路径
                      json_format:
                        start_time: "%START_TIME%"
                        method: "%REQ(:METHOD)%"
                        path: "%REQ(X-ENVOY-original-path?:PATH)%"
                        protocol: "%PROTOCOL%"
                        user_agent: "%REQ(USER-AGENT)%"
                        request_id: "%REQ(X-REQUEST-ID)%"
                        response_code: "%RESPONSE_CODE%"
                        response_flags: "%RESPONSE_FLAGS%"
                        bytes_received: "%BYTES_RECEIVED%"
                        bytes_sent: "%BYTES_SENT%"
                        duration: "%DURATION%"
                        upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                        upstream_host: "%UPSTREAM_HOST%"
                        upstream_cluster: "%UPSTREAM_CLUSTER%"
                        host: "%REQ(:AUTHORITY)%"
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: vaultwarden
                      domains:
                        - vault.smartyhero.com
                      routes:
                        - match:
                            safe_regex:
                              regex: "^/(.*)$"
                          route:
                            cluster: vaultwarden
                            regex_rewrite:
                              pattern:
                                regex: "^/(.*)$"
                              substitution: /\1
                          request_headers_to_add:
                            - header:
                                key: X-Real-IP
                                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                              append_action: ADD_IF_ABSENT
                            - header:
                                key: X-Scheme
                                value: "%PROTOCOL%"
                              append_action: ADD_IF_ABSENT
                    - name: share
                      domains:
                        - "dl.smartyhero.com"
                      routes:
                        - match:
                            prefix: /
                          route:
                            cluster: demo
                          request_headers_to_add:
                            - header:
                                key: X-Real-IP
                                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                              append_action: ADD_IF_ABSENT
                            - header:
                                key: X-Scheme
                                value: "%PROTOCOL%"
                              append_action: ADD_IF_ABSENT
                    - name: gotrue
                      domains:
                        - appflowy.smartyhero.com
                        - appflowy.smartyhero.com:443
                      cors:
                        allow_origin_string_match:
                          - safe_regex:
                              regex: "^appflowy.smartyhero.com$"
                        allow_methods: "GET, POST, OPTIONS, PUT, DELETE, PATCH"
                        allow_headers: "Content-Type, Authorization, Accept, Client-Version"
                        max_age: "3600"
                      routes:
                        - match:
                            safe_regex:
                              regex: "^/gotrue/(.*)$"
                          route:
                            cluster: gotrue
                            regex_rewrite:
                              pattern:
                                regex: "^/gotrue/(.*)$"
                              substitution: /\1
                          request_headers_to_add:
                            - header:
                                key: X-Real-IP
                                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                              append_action: ADD_IF_ABSENT
                            - header:
                                key: X-Scheme
                                value: "%PROTOCOL%"
                              append_action: ADD_IF_ABSENT
                        - match:
                            safe_regex:
                              regex: "^/minio/(.*)$"
                          route:
                            cluster: minio
                            regex_rewrite:
                              pattern:
                                regex: "^/minio/(.*)$"
                              substitution: /\1
                          request_headers_to_add:
                            - header:
                                key: X-Real-IP
                                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                              append_action: ADD_IF_ABSENT
                            - header:
                                key: X-Scheme
                                value: "%PROTOCOL%"
                              append_action: ADD_IF_ABSENT
                        - match:
                            safe_regex:
                              regex: "^/(api|ws)(.*)$"
                          route:
                            cluster: appflowy-cloud
                          request_headers_to_add:
                            - header:
                                key: X-Real-IP
                                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                              append_action: ADD_IF_ABSENT
                            - header:
                                key: X-Scheme
                                value: "%PROTOCOL%"
                              append_action: ADD_IF_ABSENT
                        - match:
                            path: /cat
                          route:
                            cluster: demo
                          request_headers_to_add:
                            - header:
                                key: X-Real-IP
                                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                              append_action: ADD_IF_ABSENT
                            - header:
                                key: X-Scheme
                                value: "%PROTOCOL%"
                              append_action: ADD_IF_ABSENT
                        - match:
                            safe_regex:
                              regex: "^/(web|assets|favicon.ico).*$"
                          route:
                            cluster: appflowy-cloud-fe
                          request_headers_to_add:
                            - header:
                                key: X-Real-IP
                                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                              append_action: ADD_IF_ABSENT
                            - header:
                                key: X-Scheme
                                value: "%PROTOCOL%"
                              append_action: ADD_IF_ABSENT
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              require_client_certificate: false # 验证客户端证书 mTls
              common_tls_context:
                tls_params:
                  tls_minimum_protocol_version: TLSv1_1 # tls最小的版本
                alpn_protocols: # 支持的http协议版本, 这里要吐槽, 默认不支持http2
                  - h2
                  - http/1.1
                tls_certificate_sds_secret_configs:
                - name: smartyhero
  clusters:
    - name: gotrue
      connect_timeout: 3s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: gotrue
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8081
    - name: appflowy-cloud
      connect_timeout: 3s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: appflowy-cloud
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8000
    - name: minio
      connect_timeout: 3s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: minio
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 9002
    - name: appflowy-cloud-fe
      connect_timeout: 3s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: appflowy-cloud-fe
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3000
    - name: demo
      connect_timeout: 3s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: demo
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
    - name: vaultwarden
      connect_timeout: 3s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: vaultwarden
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8899
```
