### ISSUE TITLE
[Bug] "Copy Link to Block" gets a wrong HOST name

### ISSUE THREAD

**Issue by veictry** [AppFlowy-IO/AppFlowy#7238]
### Bug Description

I deployed a self-host cloud in http://1.2.3.4:1234
but when I clicked "Copy Link to Block", the link we got is
"https://appflowy.com/app/f9d93ef.......?blockId=DRXQ3b"
It should be http://1.2.3.4:1234/app/......

<img width="225" alt="Image" src="https://github.com/user-attachments/assets/f010297c-b7d0-4c06-b507-dfcc95bd4bd6" />

### How to Reproduce

Deploy a self-host cloud and "npm run dev" a Web at the same time
Open web page and create a new document
Click the button shown in the description

### Expected Behavior

http://1.2.3.4:1234/app/...... 

### Operating System

Mac App/Web Page

### AppFlowy Version(s)

0.8.0

**Comment by khorshuheng** [comment]
Have you updated the web url under settings (the same page where you set the self host url)? If not set, appflowy.com will be used as the default.

**Comment by veictry** [comment]
Hi Khorshuheng,

     Thanks for your answer!
     I checked my configuration and found that the ENV VAR **AF_BASE_URL** has been set as the right value:

```
appflowy_web:
    image: node:22.13.0
    environment:
      AF_BASE_URL: http://triage-system:13030
      AF_GOTRUE_URL: http://triage-system:13030/gotrue
      AF_WS_URL: ws://triage-system:13030/ws/v1
```
Is there another variable I need to set?
